listen_addr: "127.0.0.1:8080"

server_opts:
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 60

sql_database:
  server: "postgres"
  port: 5435
  database: "tiktok_analytics"
  username: "tiktok"
  password: ""
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 5 # min
  query_timeout: 2 # sec

provider:
  type: "ensemble"
  url: "https://ensembledata.com/apis"
  token: ""

earnings:
  rate: 0.10 # dollars
  per: 1000 # views

